### ISSUE TITLE
Running your code on IndeedJobs.ipynb 'NoneType' objects

### ISSUE THREAD

**Issue by bingoong** [jmsteinw/Notebooks#1]
Sorry, I'm new into python and was trying to run your IndeedJobs.ipynb. I ran into problems running your codes. 

For example, running "seattle_info = skills_info(city = 'Seattle', state = 'WA') " gives me the following error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-7dda5b287c3e> in <module>()
----> 1 seattle_info = skills_info(city = 'Seattle', state = 'WA')

<ipython-input-10-d27d1b568a8e> in skills_info(city, state)
     75         print 'job_link_area.find_all(a) ', len(job_link_area.find_all('a'))
     76 
---> 77         job_URLS = [base_url + link.get('href') for link in job_link_area.find_all('a')] # Get the URLS for the jobs
     78 
     79         job_URLS = filter(lambda x:'clk' in x, job_URLS) # Now get just the job related URLS

TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by jmsteinw** [comment]
Most likely Indeed has changed the way links are populated. I haven't had time recently to fix the code (it was written over two years ago). You can try going through my tutorial and correct it if you want to file a pull request. 

What is going on in the code sample you showed me is that no links are being found, so you are forced to append a None type to a string type (Python doesn't like that). 

Hope that is helpful for you (I am going to close this).
